version: '2'
services:
    jhipstersampleapplication33-app:
        image: jhipstersampleapplication33
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhipstersampleapplication33-mysql:3306/jhipstersampleapplication33?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipstersampleapplication33-mysql:
        extends:
            file: mysql.yml
            service: jhipstersampleapplication33-mysql
